name: Jira Issue Transition
description: This action transitions a Jira issue to a new status.
branding:
  icon: git-merge
  color: blue
inputs:
  client-email:
    description: The email address of the user to authenticate with
    required: true
  client-token:
    description: The API token for the user to authenticate with
    required: true
  base-url:
    description: Base url of your Jira instance
    required: true
  issue-keys:
    description: The keys of the Jira issues to transition
    required: true
  transition-status:
    description: The status to transition the issues to
    required: true
  transition-comment:
    description: Automated comment to post on each transitioned issue
    required: false
  update-fields:
    description: Update fields of the issue to transition(e.g. Description, Name, or other custom fields, such as Priority or Project). Please provide these fields in JSON format
    required: false
  continue-on-error:
    description: Continue on error
    required: false
    default: false
outputs:
  issue-keys:
    description: The key of the Jira issue that was transitioned.
  transition-status:
    description: The status to which the issue was transitioned.
  status:
    description: The status of the ran action.
runs:
  using: 'node12'
  main: 'dist/index.js'